ros_control:
  # values of the servos that should be read
  read_position: false
  read_velocity: false
  read_effort: false
  read_volt_temp: false  
  VT_update_rate: 100

  # which sensors should be read
  read_buttons: false
  read_imu: false
  read_pressure: true  
  onlySensors: true

  control_loop_hz: 200

  dynamixels:
    port_info:
      port_name: /dev/ttyACM0
      baudrate: 2000000
      protocol_version: 2
    control_mode: position
    auto_torque: true    
      

  IMU:
    name: imu/data_raw
    frame: imu_frame                
