ros_control:
  read_position: true
  read_velocity: true
  read_effort: true
  read_volt_temp: true
  VT_update_rate: 100
  read_imu: true
  control_loop_hz: 200

  dynamixels:
    port_info:
      port_name: /dev/ttyACM0
      baudrate: 2000000
      protocol_version: 2
    control_mode: position
    auto_torque: true
    device_info:      

  IMU:
    name: IMU
    frame: torso                