cm730:

  # usb port which is used for the board
  device: "/dev/ttyUSB0"

  #Setzen der PID register im MX28 Ram
  setMXRam: true
  setMXRom: true

  # Augen unterdrücken
  "EyesOff": false
  # Penalty durch augen signalisieren? (Auch bei EysOff=true!)
  "EyesPenalty": true

  Minibot:
    #motors: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    motors: [28] #todo just for testing
    min_joint_id: 0
    max_joint_id: 20