cm730:

  # usb port which is used for the board
  device: "/dev/ttyUSB0"

  #Setzen der PID register im MX28 Ram
  setMXRam: true
  setMXRom: true

  # Augen unterdrücken
  "EyesOff": false
  # Penalty durch augen signalisieren? (Auch bei EysOff=true!)
  "EyesPenalty": true